spring:
  application:
    name: MiniBankTelegramBot

bot:
  name: MiniBankTelegramBot
  token: ${BOT_TOKEN}

application:
  middleService:
    url: ${MIDDLE_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true