spring:
  application:
    name: MiniBankTelegramBot
  main:
    web-application-type: none

bot:
  name: MiniBankTelegramBot
  token: ${BOT_TOKEN}

ru:
  omon4412:
    services:
      middleservice:
        url: ${MIDDLE_SERVICE_URL:http://localhost:8080}