spring:
  application:
    name: MiniBankTelegramBot

server:
  port: 8081

bot:
  name: MiniBankTelegramBot
  token: ${BOT_TOKEN}

ru:
  omon4412:
    services:
      middleservice:
        url: http://localhost:8080

